### ISSUE TITLE
json-rpc upload service

### ISSUE THREAD

**Issue by dansan** [dansan/infolog-upload#1]
Uploads should
- be authenticated
- optionally trigger an email to inform game dev if it is marked as supportticket (-> #2)
- be analyzed (-> #3)
  include:
- infolog.txt
- freeform text the user may write
- name of the tool that did the upload

suggested function signature:

``` Python
def upload(
  username, # str, lobby account
  pw, # str, lobby account
  infolog, # b64(str), infolog.txt
  client, # str, name of the connecting client software
  freetext="", # b64(str), optional, user text
  issupportticket=False, # bool, optional, user thinks this is a support case
  dict(extensions)={} # dict, optional, additional fields w/o changing API
)
return infolog_id # int, reference for this entry
```

**Comment by abma** [comment]
shouldn't a (optional) replay be uploaded/associated with the infolog.txt?

afaik infolog.txt includes the game-id which is in the replay, too.

**Comment by dansan** [comment]
40 sec late :D
The replay is found through the gameID in the infolog.txt and associated with the infolog database model.

**Comment by abma** [comment]
epic, thanks! :)
